version: "3.8"

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_ENABLE_KRAFT=true
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CLUSTER_ID=${KAFKA_CLUSTER_ID} # Unique cluster ID
    volumes:
      - /tmp/kafka:/bitnami/kafka
    networks:
      - kafka_net

  redis:
    image: bitnami/redis
    container_name: redis
    networks:
      - redis_net
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - /tmp/redis:/bitnami/redis

  mysql:
    image: bitnami/mysql:latest
    container_name: mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /tmp/mysql/lib:/var/lib/mysql
      #- /tmp/mysql/data:/bitnami/mysql
      - ./DBs/mysql/init.sql:/tmp/init.sql
      - ./DBs/mysql/startup.sh:/docker-entrypoint-initdb.d/startup.sh

    networks:
      - mysql_net
    command: >
      bash -c "/opt/bitnami/scripts/mysql/entrypoint.sh /opt/bitnami/scripts/mysql/run.sh"

networks:
  kafka_net:
    driver: bridge
  redis_net:
    driver: bridge
  mysql_net:
    driver: bridge


  