version: '3.9'

services:
  micro_postgres:
    image: bitnami/postgresql:latest
    container_name: micro_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

    networks:
      - micro_net

  service1:
    build:
      context: ./Microservices/service1
    container_name: service1
    ports:
      - "8081:8081"
    environment:
      - SERVICE2_URL=http://service2:8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otlp-kafka-bridge:5000
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_HEADERS=application=distributed_tracing
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=distributed_tracing
      - OTEL_SERVICE_NAME=microservice1
      - OTEL_SERVICE_VERSION=1.0.0
      - OTEL_LOGS_EXPORTER=none
      - OTEL_METRICS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=otlp

    depends_on:
      - service2
    networks:
      - micro_net

  service2:
    build:
      context: ./Microservices/service2
    container_name: service2
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://micro_postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otlp-kafka-bridge:5000
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_HEADERS=application=distributed_tracing
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=distributed_tracing
      - OTEL_SERVICE_NAME=microservice1
      - OTEL_SERVICE_VERSION=1.0.0
      - OTEL_LOGS_EXPORTER=none
      - OTEL_METRICS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=otlp

    depends_on:
      - micro_postgres
    networks:
      - micro_net

networks:
  micro_net:
    driver: bridge
