version: "3.9"

services:
  kafka:
    image: dt/kafka-cluster:latest
    container_name: ${KAFKA_HOST}
    #temporary for code use start
    ports:
      - "9092:9092"
      - "9093:9093"
    #temporary for code use end
    environment:
      - KAFKA_ENABLE_KRAFT=true
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_LISTENERS=${KAFKA_CFG_LISTENERS}
      - KAFKA_CFG_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP}
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}
      - KAFKA_CFG_CLUSTER_ID=${KAFKA_CLUSTER_ID}
      - KAFKA_TOPICS=${KAFKA_TOPICS}
    volumes:
      - /tmp/kafka:/bitnami/kafka
    networks:
      - kafka_net

  redis:
    image: bitnami/redis
    container_name: ${REDIS_HOST}
    networks:
      - redis_net
    restart: always
    
    #temporary for code use start
    ports:
      - "6379:6379"
    #temporary for code use end

    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/bitnami/redis

  postgres:
    image: bitnami/postgresql:latest
    container_name: ${POSTGRES_HOST}

    #temporary for code use start
    ports:
      - "5432:5432"
    #temporary for code use end

    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DATABASE}
    volumes:
      - /tmp/postgressql/data:/bitnami/postgresql
      - ./DBs/postgres:/docker-entrypoint-initdb.d
    networks:
      - postgres_net

  redis-helper:
    image: dt/redis-helper:latest
    container_name: ${REDIS_HELPER_HOST}
    depends_on:
      - redis
      - postgres

    networks:
      - redis_net
      - postgres_net
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - TABLE_NAME=${TABLE_NAME}
      - SCHEDULE_INTERVAL=${SCHEDULE_INTERVAL}

  otlp-kafka-bridge_1:
    image: dt/otlp-kafka-bridge:latest
    container_name: ${OTLP_KAFKA_BRIDGE_HOST}_1
    restart: always
    depends_on:
      - redis
      - kafka
      - postgres
    networks:
      - redis_net
      - kafka_net
      - postgres_net
      - micro_net
      - lb_net
    environment:
      - HOST=${OTLP_KAFKA_BRIDGE_HOSTNAME}
      - PORT=${OTLP_KAFKA_BRIDGE_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - TABLE_NAME=${TABLE_NAME}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
      - KAFKA_AUTO_OFFSET_RESET=${KAFKA_AUTO_OFFSET_RESET}
      - KAFKA_ENABLE_AUTO_COMMIT=${KAFKA_ENABLE_AUTO_COMMIT}

  otlp-kafka-bridge_lb:
    image: dt/otlp-kafka-bridge_lb:latest
    container_name: ${OTLP_KAFKA_BRIDGE_HOST}
    restart: always
    environment:
      - NGINX_OTLP_KAFKA_BRIDGE_LB_UPSTREAM=${NGINX_OTLP_KAFKA_BRIDGE_LB_UPSTREAM}
    networks:
      - lb_net
      - micro_net
    depends_on:
      - otlp-kafka-bridge_1
      #- otlp-kafka-bridge_2

# microservices - testing purposes only
  micro_postgres:
    image: bitnami/postgresql:latest
    container_name: micro_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - micro_net

  service1:
    build:
      context: ./Microservices/service1
    container_name: service1
    ports:
      - "8081:8081"
    environment:
      - SERVICE2_URL=http://service2:8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_HEADERS=application=distributed_tracing
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=distributed_tracing
      - OTEL_SERVICE_NAME=microservice1
      - OTEL_SERVICE_VERSION=1.0.0
      - OTEL_LOGS_EXPORTER=none
      - OTEL_METRICS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=otlp
    depends_on:
      - service2
      - otlp-kafka-bridge_lb
    networks:
      - micro_net
      - lb_net

  service2:
    build:
      context: ./Microservices/service2
    container_name: service2
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://micro_postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}
      - OTEL_RESOURCE_ATTRIBUTES=${OTEL_RESOURCE_ATTRIBUTES}
      - OTEL_SERVICE_NAME=microservice2
      - OTEL_SERVICE_VERSION=1.0.0
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp

    depends_on:
      - micro_postgres
      #- otlp-kafka-bridge_lb
      - otlp-kafka-bridge_1
    networks:
      - micro_net
      - lb_net




networks:
  kafka_net:
    driver: bridge
  redis_net:
    driver: bridge
  postgres_net:
    driver: bridge
  micro_net:
    driver: bridge
  lb_net:
    driver: bridge

volumes:
  redis_data:
    driver: local